#!/usr/bin/env python3
"""
Measure WCAG 2.1 contrast for every text/background pair the app actually uses,
and write Docs/07-Contrast-Report.md.

The point is that the accessibility claims in the Task 5 rationale are
measured and reproducible rather than asserted. Run it again after any palette
change and the report regenerates.

    python tools/contrast.py
"""

import io
import os
import sys

# The report uses ✅/❌ and the Windows console defaults to cp1252.
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GROUND = "#040606"
SURFACE1 = "#0C1010"
SURFACE2 = "#151A1A"
MAGENTA_DEEP = "#461E3C"
MAGENTA = "#4D2646"
GREEN = "#1B7A4A"
MINT = "#7FD9A8"
WHITE = "#FFFFFF"

# Text colours that are semi-transparent white are flattened against their
# background first — the ratio a user actually sees, not the ratio of the
# nominal colour.
PAIRS = [
    # (label, foreground, background, alpha, context, body-size?)
    ("Body white on ground",            WHITE, GROUND,       1.00, "Default body and headings", True),
    ("Secondary white 78% on ground",   WHITE, GROUND,       0.78, "Supporting body copy", True),
    ("Muted white 62% on ground",       WHITE, GROUND,       0.62, "Metadata, hints, captions", True),
    ("Mint on ground",                  MINT,  GROUND,       1.00, "Links, active nav, times", True),
    ("White on surface-1",              WHITE, SURFACE1,     1.00, "Card text", True),
    ("Muted white 62% on surface-1",    WHITE, SURFACE1,     0.62, "Card metadata", True),
    ("White on surface-2",              WHITE, SURFACE2,     1.00, "Overlay and input text", True),
    ("Mint on surface-2",               MINT,  SURFACE2,     1.00, "Overlay accents", True),
    ("Ground on mint",                  "#04120B", MINT,     1.00, "Primary button label", True),
    ("White on deep magenta",           WHITE, MAGENTA_DEEP, 1.00, "Text over background artwork", True),
    ("Mint on deep magenta",            MINT,  MAGENTA_DEEP, 1.00, "Accents over artwork", True),
    ("White on magenta light",          WHITE, MAGENTA,      1.00, "Text over background artwork", True),
    ("White on festival green",         WHITE, GREEN,        1.00, "Green chips and confirmations", True),
    # The rejected combination, kept in the report because a rejection with a
    # number behind it is worth more than a rule with none.
    ("Magenta #8B3A8B on ground",       "#8B3A8B", GROUND,   1.00, "REJECTED for text — decoration only", True),
]


def srgb_to_linear(c):
    c = c / 255.0
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def luminance(rgb):
    r, g, b = (srgb_to_linear(c) for c in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def flatten(fg, bg, alpha):
    """Composite a semi-transparent foreground onto its background."""
    return tuple(round(f * alpha + b * (1 - alpha)) for f, b in zip(fg, bg))


def ratio(fg_hex, bg_hex, alpha=1.0):
    fg, bg = hex_to_rgb(fg_hex), hex_to_rgb(bg_hex)
    if alpha < 1.0:
        fg = flatten(fg, bg, alpha)
    l1, l2 = luminance(fg), luminance(bg)
    lo, hi = sorted((l1, l2))
    return (hi + 0.05) / (lo + 0.05)


def grade(r, large=False):
    aa = 3.0 if large else 4.5
    aaa = 4.5 if large else 7.0
    if r >= aaa:
        return "AAA", "Pass"
    if r >= aa:
        return "AA", "Pass"
    return "—", "FAIL"


def main():
    rows = []
    failures = 0
    for label, fg, bg, alpha, context, _ in PAIRS:
        r = ratio(fg, bg, alpha)
        level, result = grade(r)
        expected_fail = "REJECTED" in context
        if result == "FAIL" and not expected_fail:
            failures += 1
        mark = "✅" if result == "Pass" else ("⛔" if expected_fail else "❌")
        rows.append(f"| {label} | `{fg}`{'' if alpha == 1 else f' @ {int(alpha*100)}%'} | "
                    f"`{bg}` | **{r:.2f}:1** | {level} | {mark} {result} | {context} |")

    doc = f"""# Contrast Report

**Generated by `tools/contrast.py` — do not edit by hand.** Re-run the script after any
palette change and this file regenerates.

Measured against **WCAG 2.1 SC 1.4.3 (Contrast Minimum)**. The threshold for normal-size
text is **4.5:1** for AA and **7:1** for AAA. Semi-transparent text is flattened against
its background first, so every figure below is the ratio a user actually sees rather than
the ratio of the nominal colour.

These figures are quotable in the Task 5 rationale.

| Combination | Foreground | Background | Ratio | Level | Result | Where it is used |
|---|---|---|---|---|---|---|
{chr(10).join(rows)}

## What this means for the design

**Text is white or mint only.** Both clear AAA on every surface in the app.

**Magenta never carries type.** The campaign's magenta measures 2.98:1 on the ground
colour — it fails AA outright. It is used for background forms, borders and texture, and
is structurally excluded from text: there is no magenta text token in `tokens.css` to
reach for.

**The background artwork sits under a scrim.** The section artwork contains lighter
magenta forms. Rather than trust that text never lands on one, every screen draws a
78–88% ground-colour scrim over the artwork, which holds the ratios in the table above
regardless of what is behind them. In high-contrast mode the artwork is removed entirely.

**High-contrast mode goes further.** It lifts muted text to 88% white, raises card
surfaces to pure black, and strengthens every border — for a user who has asked for
maximum legibility, decoration is not worth a contrast risk.

## Beyond contrast

Contrast is one success criterion. The app also addresses:

- **1.4.4 Resize text** — three text sizes in Settings, up to 21px body, without loss of content.
- **1.4.11 Non-text contrast** — nav active state carries a bar and `aria-current`, not colour alone; map pins carry distinct shapes per type.
- **2.1.1 Keyboard** — every control is a native button, link, input or range; carousels take arrow keys.
- **2.4.7 Focus visible** — a single 3px mint focus ring, never removed.
- **2.5.5 Target size** — 44px minimum on every interactive element.
- **2.3.3 Animation from interactions** — `prefers-reduced-motion` respected, plus an in-app Reduce Motion setting.
- **3.3.2 Labels or instructions** — form labels sit above fields, never placeholder-only.
- **4.1.3 Status messages** — a live region announces route changes, toasts and setting changes.

**Typeface:** body copy is Atkinson Hyperlegible, designed by the Braille Institute for
readers with low vision. The pixel display face is restricted to headings and short
labels at 14px and above, and never sets running text.
"""

    dst = os.path.join(ROOT, "Docs", "07-Contrast-Report.md")
    with open(dst, "w", encoding="utf-8") as f:
        f.write(doc)

    for row in rows:
        print(row)
    print(f"\nWritten to {os.path.relpath(dst, ROOT)}")
    print(f"Unexpected failures: {failures}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
